[package]
name = "webd"
version = "0.1.0"
authors = ["Jeffrey McAteer <jeffrey.p.mcateer@gmail.com>"]
edition = "2018"


[dependencies]
#authenticator = "0.3"
authenticator = { path = "libs/authenticator" }
base64 = "0.12.3"
getopts = "0.2"
sha2 = "0.7"

